name: nbterm-dev
channels:
    - conda-forge
dependencies:
    - pip
    - prompt_toolkit >=3.0.16
    - typer
    - pygments
    - rich
    - mypy
    - flake8
    - black
    - pytest
    - ipykernel
    - pip:
      - git+https://github.com/davidbrochart/kernel_driver.git#egg=kernel_driver
